# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/PMPP',
                'doc_host': 'https://tripathysagar.github.io',
                'git_url': 'https://github.com/tripathysagar/PMPP',
                'lib_path': 'PMPP'},
  'syms': {'PMPP.core': {'PMPP.core.foo': ('core.html#foo', 'PMPP/core.py')}}}
