# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/PMPP',
                'doc_host': 'https://tripathysagar.github.io',
                'git_url': 'https://github.com/tripathysagar/PMPP',
                'lib_path': 'PMPP'},
  'syms': { 'PMPP.NumbaSimSetup': { 'PMPP.NumbaSimSetup.device': ('numbasimsetup.html#device', 'PMPP/NumbaSimSetup.py'),
                                    'PMPP.NumbaSimSetup.dim': ('numbasimsetup.html#dim', 'PMPP/NumbaSimSetup.py'),
                                    'PMPP.NumbaSimSetup.has_gpu': ('numbasimsetup.html#has_gpu', 'PMPP/NumbaSimSetup.py'),
                                    'PMPP.NumbaSimSetup.is_sim': ('numbasimsetup.html#is_sim', 'PMPP/NumbaSimSetup.py'),
                                    'PMPP.NumbaSimSetup.perf': ('numbasimsetup.html#perf', 'PMPP/NumbaSimSetup.py'),
                                    'PMPP.NumbaSimSetup.set_sim': ('numbasimsetup.html#set_sim', 'PMPP/NumbaSimSetup.py'),
                                    'PMPP.NumbaSimSetup.test_close': ('numbasimsetup.html#test_close', 'PMPP/NumbaSimSetup.py')}}}
