"""Check if the Numba CUDA simulator is enabled"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_NumbaSimSetup.ipynb.

# %% auto 0
__all__ = ['SYS_PROMPT', 'MANIM_PROMPT', 'is_sim', 'set_sim', 'cuda_avail', 'device', 'test_close', 'is_colab', 'dim']

# %% ../nbs/00_NumbaSimSetup.ipynb 2
import os
import sys

# %% ../nbs/00_NumbaSimSetup.ipynb 3
def is_sim():
    """Check if we're running in a simulator by checking the NUMBA_ENABLE_CUDASIM environment variable"""
    return os.environ.get('NUMBA_ENABLE_CUDASIM') == '1'

# %% ../nbs/00_NumbaSimSetup.ipynb 6
def set_sim():
    """ Seting up Numba CUDA simulator"""
    if not is_sim():
        os.environ['NUMBA_ENABLE_CUDASIM'] = '1'

# %% ../nbs/00_NumbaSimSetup.ipynb 9
def cuda_avail(): 
    from numba import cuda
    return  cuda.is_available()


# %% ../nbs/00_NumbaSimSetup.ipynb 14
def device(x):
    return "cuda" if hasattr(x, 'copy_to_host') else "cpu"

# %% ../nbs/00_NumbaSimSetup.ipynb 16
import numpy as np

def test_close(a, b, tol=1e-4):
    return np.allclose(a, b, rtol=tol, atol=tol)


# %% ../nbs/00_NumbaSimSetup.ipynb 18
def is_colab():
    "check is running in colab"
    return 'google.colab' in sys.modules

# %% ../nbs/00_NumbaSimSetup.ipynb 20
import math
def dim(base:float, th:float):
    return math.ceil(base/th)

# %% ../nbs/00_NumbaSimSetup.ipynb 22
SYS_PROMPT = """
I'm learning GPU programming using the PMPP book (located at PMPP/PMPP.md). Help me work through it systematically.

My setup:
- Using Numba CUDA simulator (CPU-only machine)
- Can test on Colab/Kaggle with real GPUs
- Comfortable with Python and C/C++

For each chapter/section:
1. Read and summarize the key concepts
2. Show any relevant figures/diagrams from the book
3. Help me implement the examples in Numba (guide me, don't write full code unless I ask)
4. Create practice exercises to reinforce learning
5. Connect concepts to ML/deep learning applications where relevant


Use these tools to navigate the book:
- `view` to read sections
- `rg` to search for topics
- Show images when referenced (e.g., ![](_page_XX_Figure_X.jpeg))

Let's continue with Chapter 3: Multidimensional grids and data.
"""


# %% ../nbs/00_NumbaSimSetup.ipynb 23
MANIM_PROMPT = """System prompt for MANIM

**Scene structure:**
- List the stages/steps to show (e.g., Stage 1: X, Stage 2: Y)
- Specify transitions between stages
- Each scene should have a wait around 4 seconds

**Visual requirements:**
- Canvas layout: where elements should be positioned (LEFT, RIGHT, UP, DOWN, ORIGIN)
- Colors: specific color scheme or let AI choose
- Size: pixel/element sizes
- Labels: what text/labels to show

**Animation style:**
- Pacing: fast preview or slow educational
- Highlight style: how to emphasize important elements
- Transitions: FadeIn, FadeOut, Transform, etc.

**Mandatory layout rules (IMPORTANT):**
1. Fade out ALL elements before each new stage — prevents overlap
2. Position text labels with buff=0.5 minimum — prevents crowding
3. Use to_edge() for info panels — keeps them out of the way
4. Font sizes: titles ≤ 28, labels ≤ 24, annotations ≤ 20
5. Never position text over figures — use LEFT/RIGHT/DOWN edges
6. Track all created objects and explicitly FadeOut before next stage

**Example values (if applicable):**
- Grid size: 5×5
- Block size: 3×3
- Sample data: random colors, specific numbers, etc.

**Output format:**
- Single Scene class"""

